name: Deploy image to Quay.io

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        description: Image Name
        type: string
      image_tag:
        required: true
        description: Image Version
        type: string

env:
  PAYLOAD_IMAGE_NAME: ${{ inputs.image_name }}
  PAYLOAD_IMAGE_TAG: ${{ inputs.image_tag }}
  PAYLOAD_REPOSITORY: ${{ github.repository }}

permissions:
  attestations: write
  id-token: write

jobs:
  deploy_to_quay:
    environment:
      name: Quay.io
      url: ${{ steps.out.outputs.release-workflow-url }}
    outputs:
      release-workflow-id: ${{ steps.out.outputs.release-workflow-id }}
      release-workflow-url: ${{ steps.out.outputs.release-workflow-url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          repository: ${{ env.PAYLOAD_REPOSITORY }}
          run-id: ${{ github.run_id}}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        id: attest_build_provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: artifact.tar.gz

      - uses: actions/create-github-app-token@v1
        id: app-token
        name: Create GitHub App Token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          repositories: quarkiverse-release

      - name: Invoke Deploy to Quay workflow
        run: |
          gh workflow run deploy-quay.yml -R quarkiverse/quarkiverse-release \
            -f image_name=${PAYLOAD_IMAGE_NAME} \
            -f image_tag=${PAYLOAD_IMAGE_TAG} \
            -f github_repository=${GH_REPO} \
            -f run_id=${GH_RUN_ID}
          
          echo "WORKFLOW_RUN_NAME=Deploy ${PAYLOAD_IMAGE_NAME} ${PAYLOAD_IMAGE_TAG} to Quay.io" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
          GH_RUN_ID: ${{ github.run_id }}
          ARTIFACT_NAME: ${{ github.event.repository.name }}

      - name: Output workflow execution URL
        id: out
        run: |
          # Wait for the deploy-quay.yml workflow to start
          sleep 10
          # Get the URL of the release workflow (MUST match the workflow's run-name)
          RELEASE_WORKFLOW_DATA=$(gh run list --workflow deploy-quay.yml -R quarkiverse/quarkiverse-release --json databaseId,name,url -q ".[] | select(.name == \"${RELEASE_WORKFLOW_RUN_NAME}\")" --limit 1)
          RELEASE_WORKFLOW_ID=$(jq -r '.databaseId' <<< $RELEASE_WORKFLOW_DATA)
          RELEASE_WORKFLOW_URL=$(jq -r '.url' <<< $RELEASE_WORKFLOW_DATA)
          echo "release-workflow-id=$RELEASE_WORKFLOW_ID" >> $GITHUB_OUTPUT
          echo "release-workflow-url=$RELEASE_WORKFLOW_URL" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Wait for the deployment workflow to finish
        run: |
          gh run watch ${RELEASE_WORKFLOW_ID} -R quarkiverse/quarkiverse-release --exit-status
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          RELEASE_WORKFLOW_ID: ${{ steps.out.outputs.release-workflow-id }}

      - name: Display logs if failed
        if: failure()
        run: |
          gh run view ${RELEASE_WORKFLOW_ID} -R quarkiverse/quarkiverse-release --log-failed
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          RELEASE_WORKFLOW_ID: ${{ steps.out.outputs.release-workflow-id }}
